# # Use an official Python runtime as a parent image
# FROM python:3.9-slim

# # Set the working directory in the container
# WORKDIR /app

# # Copy the current directory contents into the container at /app
# COPY . /app

# # Install build dependencies
# RUN apt-get update && apt-get install -y \
#     build-essential \
#     && rm -rf /var/lib/apt/lists/*

# # Install any needed packages specified in requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt

# # Make port 8000 available to the world outside this container
# EXPOSE 8000

# # Define environment variable
# ENV FLASK_APP=api/index.py
# ENV FLASK_ENV=production

# # Download the Whisper model file if it doesn't exist
# RUN if [ ! -f ggml-model-whisper-tiny.bin ]; then wget https://ggml.ggerganov.com/ggml-model-whisper-tiny.bin; fi

# # Run gunicorn when the container launches
# CMD ["gunicorn", "index:app", "--bind", "0.0.0.0:8000"]

